---
config:
  theme: neutral
---
sequenceDiagram
        actor User as :Customer
        participant FE as :WebBrowser
        participant Ctrl as :BookingController
        participant Service as :BookingService
        participant Repo as :SeatRepository
        participant showtime as :ShowtimeRepository
        participant Ticket as :TicketRepository
        participant VNPay as :PaymentService

        User ->> FE: chooseCinema(cinemaID, roomID)
        activate FE
        FE ->> Ctrl: chooseCinema(cinemaID, roomID)
        activate Ctrl
        Ctrl ->> Service: getShowtimeList(cinemaID, roomID)
        activate Service
        Service ->> showtime: getShowtimeList(cinemaID, roomID)
        activate showtime
        showtime -->> Service: Danh sách suất chiếu 
        deactivate showtime
        Service  -->> Ctrl: Danh sách suất chiếu 
        deactivate Service
        Ctrl -->> FE: Danh sách suất chiếu 
        deactivate Ctrl
        FE -->> User: Danh sách suất chiếu 
        FE ->> Ctrl: getSeatList(cinemaID, showtimeID)
        activate Ctrl
        Ctrl ->> Service: getSeatList(cinemaID, showtimeID)
        activate Service
        Service ->> Repo: getSeatList(cinemaID, showtimeID)
        activate Repo
        Repo -->> Service: Danh sách trạng thái ghế ngồi 
        deactivate Repo
        Service -->> Ctrl: Danh sách trạng thái ghế ngồi 
        deactivate Service
        Ctrl -->> FE: Danh sách trạng thái ghế ngồi
        deactivate Ctrl
        FE -->> User: Danh sách trạng thái ghế ngồi

        User ->> FE: chooseSeat(seatID)
        FE ->> Ctrl: chooseSeat(seatID)
        activate Ctrl
        Ctrl ->> Service: checkSeatStatus(seatID)
        activate Service
        Service ->> Repo: getSeatStatus(seatID)
        activate Repo
        Repo -->> Service: Trạng thái ghế được chọn
        deactivate Repo
        %% deactivate Service
        %% deactivate Ctrl
        alt Ghế đã được đặt
            %% activate Service
            Service -->> Ctrl: Thông báo không đặt được ghế
            %% deactivate Service 
            %% activate Ctrl
            Ctrl -->> FE: Thông báo không đặt được ghế
            deactivate Ctrl
            FE -->> User: Thông báo không đặt được ghế
        else Ghế trống
            %% activate Service
            Service ->> Repo: changeSeatStatus(seadID, "đang chờ")
            Service ->> Ticket: create(seatID, cinemaID, showtimeID)
            activate Ticket
            Ticket -->> Service: ID của vé vừa tạo
            deactivate Ticket
            Service -->> Ctrl: ID của vé vừa tạo
            deactivate Service
            activate Ctrl
            Ctrl -->> FE: ID của vé vừa tạo
            deactivate Ctrl
            FE -->> User: ID của vé vừa tạo
            Note over User, VNPay: Xem chi tiết trong biểu đồ "Thanh Toán"
            %% User ->> FE: pay(ticketID, voucherID)
            %% FE ->> Ctrl: pay(ticketID, voucherID) 
            %% Ctrl ->> Ctrl: createInvoice(ticketID)
            %% Ctrl ->> VNPay: pay(invoice)
            activate Ctrl
            Ctrl ->> VNPay: getPaymentResponse(ticketId)
            activate VNPay
            VNPay -->> Ctrl: Kết quả thanh toán
            deactivate VNPay
            Ctrl -->> FE: Kết quả thanh toán
            deactivate Ctrl
            FE -->> User: Kết quả thanh toán
        end
    deactivate FE

