---
title: Hello Title
config:
  theme: "neutral"
---

sequenceDiagram
actor User
User ->> Web Browser: Gửi yêu cầu mua vé
activate Web Browser
Web Browser ->> Server: Kiểm tra trạng thái ghế ngồi
activate Server
Server ->> DB: Lấy thông tin trạng thái ghế ngồi
activate DB
DB -->> Server: Dữ liệu trạng thái ghế ngồi
deactivate DB
Server -->> Web Browser: Dữ liệu trạng thái ghế ngồi
deactivate Server
Web Browser -->> User: giao diện chọn ghế
deactivate Web Browser

    User ->> Web Browser: Lựa chọn ghế và gửi yêu cầu đặt
    activate Web Browser
    Web Browser ->> Server: Gửi yêu cầu đặt ghế
    activate Server
    Server ->> DB: Kiểm tra trạng thái ghế được chọn
    activate DB
    DB -->> Server: Trạng thái ghế được chọn
    deactivate DB

    alt Ghế đã được đặt
    Server -->> Web Browser: Lỗi đặt ghế
    Web Browser -->> User: Giao diện lỗi đặt ghế (ghế đã được đặt)

    else Ghế trống
        Server ->> DB: Giữ ghế tạm thời
        activate DB
        DB -->> Server: Cập nhật thành công
        deactivate DB
        Server -->> Web Browser: Chọn ghế thành công
        Web Browser -->> User: Giao diện chọn Voucher
        deactivate Web Browser
        User ->> Web Browser: Lựa chọn Voucher (opt) và gửi yêu cầu thanh toán
        activate Web Browser
        Web Browser ->> Server: Gửi yêu cầu thanh toán
        Server ->> Bank: Yêu cầu lập hóa đơn và mã QR thanh toán
        activate Bank
        par Quá trình thanh toán
            Bank ->> User : Yêu cầu thanh toán
            User -->> Bank : Thông tin chuyển khoản
        and Server đếm ngược
            Server -->> Server: Đếm ngược
        end

        alt Thanh toán thành công
            Bank -->> Server: Thanh toán thành công
            Server ->> DB: Cập nhật ghế
            activate DB
            DB -->> Server: Cập nhật thành công
            deactivate DB
            Server -->> Web Browser: Thanh toán thành công
            Web Browser -->> User: Giao diện thanh toán thành công + vé online

        else Thanh toán thất bại/ Quá thời gian
            Bank -->> Server: Thanh toán thất bại
            Server -->> DB: Bỏ giữ ghế
            activate DB
            DB -->> Server: Cập nhật thành công
            deactivate DB
            Server -->> Web Browser: Thanh toán thất bại
            deactivate Server
            Web Browser -->> User : Giao diện thanh toán thất bại
            deactivate Web Browser
        end
    end

