sequenceDiagram

actor User

participant WebBrowser
participant Auth
participant Database

User ->> WebBrowser: EnterEmailAndPassword()
activate WebBrowser
WebBrowser ->> Auth: SignInRequest(email, password)
activate Auth

Auth ->> Database: GetUserByEmail(email)
activate Database
Database -->> Auth: userData or null
deactivate Database

alt User not found
    Auth -->> WebBrowser : error("Account don't exist")
    WebBrowser -->> User: ShowErrorMessage()

else User existing
    Auth ->> Auth: VerifyPassword(password, userData)
    alt Password incorrect
        Auth -->> WebBrowser: error("Password incorrect")
        WebBrowser -->> User: ShowErrorMessage()

    else Password correct
        activate Auth
        Auth ->> Auth: CreateSession(userData)
        Auth -->> WebBrowser: sessionData
        deactivate Auth
        activate WebBrowser
        WebBrowser ->> WebBrowser: UpdateSession()
        WebBrowser -->> User: redirectToHomePage()
        deactivate WebBrowser
    end
    deactivate Auth
end
deactivate WebBrowser
