sequenceDiagram

actor User

participant Application
participant Auth
participant Database

User ->> Application: EnterEmailAndPassword()
activate Application
Application ->> Auth: SignInRequest(email, password)
activate Auth

Auth ->> Database: GetUserByEmail(email)
activate Database
Database -->> Auth: userData or null
deactivate Database

alt User not found
    Auth -->> Application : error("Account don't exist")
    Application -->> User: ShowErrorMessage()

else User existing
    Auth ->> Auth: VerifyPassword(password, userData)
    alt Password incorrect
        Auth -->> Application: error("Password incorrect")
        Application -->> User: ShowErrorMessage()

    else Password correct
        activate Auth
        Auth ->> Auth: CreateSession(userData)
        Auth -->> Application: sessionData
        deactivate Auth
        activate Application
        Application ->> Application: UpdateSession()
        Application -->> User: redirectToHomePage()
        deactivate Application
    end
    deactivate Auth
end
deactivate Application
